/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package front;

import connexion.Connexion;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author Badr
 */
public class Register extends javax.swing.JFrame {
  private static final String regex = "^[\\w!#$%&'*+/=?`{|}~^-]+(?:\\.[\\w!#$%&'*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}";
	 private static final String regexT= "^[0-9]*$" ;
	  private static final String regexN= "^[a-zA-Z]*$" ;
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
         Toolkit toolkit= getToolkit();
        Dimension size= toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2 , size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        addresse = new javax.swing.JTextField();
        registerbtn = new javax.swing.JButton();
        gobackbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        confirmpassword = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernameKeyReleased(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 480, -1));

        firstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnameFocusLost(evt);
            }
        });
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        firstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                firstnameKeyReleased(evt);
            }
        });
        jPanel1.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 190, -1));

        lastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lastnameKeyReleased(evt);
            }
        });
        jPanel1.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 170, -1));

        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phoneKeyReleased(evt);
            }
        });
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 170, -1));

        addresse.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addresseFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addresseFocusLost(evt);
            }
        });
        addresse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addresseKeyReleased(evt);
            }
        });
        jPanel1.add(addresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 190, -1));

        registerbtn.setBackground(new java.awt.Color(0, 0, 0));
        registerbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registerbtn.setForeground(new java.awt.Color(255, 255, 255));
        registerbtn.setText("Submit");
        registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbtnActionPerformed(evt);
            }
        });
        jPanel1.add(registerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 90, 30));

        gobackbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/front/back-arrow (1).png"))); // NOI18N
        gobackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobackbtnActionPerformed(evt);
            }
        });
        jPanel1.add(gobackbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First_name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 57, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Last_name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 37, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Confirmer");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, 40));
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 190, -1));
        jPanel1.add(confirmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 170, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/front/button.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 30, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/front/register.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 190, 140));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/front/abstract-uv-ultraviolet-light-composition.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public boolean fieldvalide(String field) {
		Pattern p = Pattern.compile(regexN);
		Matcher matcher = p.matcher(field);
		return matcher.matches();
	}
 public boolean emailvalide(String email) {
		Pattern p = Pattern.compile(regex);
		Matcher matcher = p.matcher(email);
		return matcher.matches();
	}
    
    public boolean phonevalide(String phone) {
		Pattern p = Pattern.compile(regexT);
		Matcher matcher = p.matcher(phone);
		return matcher.matches();
	}
    public void clear(){
    firstname.setText("");
    lastname.setText("");
    addresse.setText("");
    phone.setText("");
    username.setText("");
    password.setText("");
    confirmpassword.setText("");
    }
    
    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void registerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtnActionPerformed
       String usern=username.getText();
       String first_n=firstname.getText();
       String last_n=lastname.getText();
       String addr=addresse.getText();
       String teleph=phone.getText();
       String pwd=password.getText();
       String pwdconf=confirmpassword.getText();
      
        String req="insert into users(first_name,last_name,address,phone,username,password) values(?,?,?,?,?,?)";
        try {
            PreparedStatement ps=Connexion.getCon().prepareStatement(req);
            ps.setString(1, first_n);
             ps.setString(2, last_n);
              ps.setString(3, addr);
               ps.setString(4, teleph);
                ps.setString(5, usern);
                 ps.setString(6, pwd);
                 if(usern.equals("") || first_n.equals("") || last_n.equals("")){
                 JOptionPane.showMessageDialog(this, " please fill all the fields ");
                 }
                 else if(pwd.equals("") ? pwdconf !=null : !pwd.equals(pwdconf)){
                     JOptionPane.showMessageDialog(this, "please confirm password");
                     }
                 else if(ps.executeUpdate()==1){
                     
                     JOptionPane.showMessageDialog(this, "user has been added successfully");
                     clear();
                 }else{
                 JOptionPane.showMessageDialog(this, "oops something went wrong");
                 }
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_registerbtnActionPerformed

    private void gobackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobackbtnActionPerformed
       Login login=new Login();
       login.setVisible(true);
       dispose();
    }//GEN-LAST:event_gobackbtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void firstnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameFocusLost
        if(firstname.getText().equals("")){
            firstname.setText("FIrst_name");
            firstname.setForeground(Color.gray);
        }
    }//GEN-LAST:event_firstnameFocusLost

    private void firstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameFocusGained
        if(firstname.getText().equals("First_name")){
           firstname.setText("");
            firstname.setForeground(Color.black);
        }
    }//GEN-LAST:event_firstnameFocusGained

    private void addresseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addresseFocusGained
       if(lastname.getText().equals("Last_name")){
           lastname.setText("");
            lastname.setForeground(Color.black);
        }
    }//GEN-LAST:event_addresseFocusGained

    private void addresseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addresseFocusLost
        if(lastname.getText().equals("")){
            lastname.setText("Last_name");
            lastname.setForeground(Color.gray);
        }
    }//GEN-LAST:event_addresseFocusLost

    private void phoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyReleased
       if(!phonevalide(phone.getText())) {
					phone.setBorder(new LineBorder(Color.red,2));
				}else {
					phone.setBorder(new LineBorder(Color.green,1));
				}
    }//GEN-LAST:event_phoneKeyReleased

    private void addresseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addresseKeyReleased
         if(!emailvalide(addresse.getText())) {
					addresse.setBorder(new LineBorder(Color.red,2));
				}else {
					addresse.setBorder(new LineBorder(Color.green,1));
				}
    }//GEN-LAST:event_addresseKeyReleased

    private void firstnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstnameKeyReleased
 if(!fieldvalide(firstname.getText())) {
					firstname.setBorder(new LineBorder(Color.red,2));
				}else {
					firstname.setBorder(new LineBorder(Color.green,1));
				
 }    }//GEN-LAST:event_firstnameKeyReleased

    private void lastnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastnameKeyReleased
       if(!fieldvalide(lastname.getText())) {
					lastname.setBorder(new LineBorder(Color.red,2));
				}else {
					lastname.setBorder(new LineBorder(Color.green,1));
				
 } 
    }//GEN-LAST:event_lastnameKeyReleased

    private void usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyReleased
       if(!fieldvalide(username.getText())) {
					username.setBorder(new LineBorder(Color.red,2));
				}else {
					username.setBorder(new LineBorder(Color.green,1));
				
 } 
    }//GEN-LAST:event_usernameKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addresse;
    private javax.swing.JPasswordField confirmpassword;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton gobackbtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastname;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phone;
    private javax.swing.JButton registerbtn;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
